### ISSUE TITLE
Session and break length adjust

### ISSUE THREAD

**Issue by haukegr** [by-Tim-Christiansen/pomodoro-clock#17]
![image](https://user-images.githubusercontent.com/21065939/34995883-23ad68b4-fad8-11e7-9394-c06f4ea255db.png)
The numbers are a little bit too small compared to - and +, at least in my opinion.
What do we want to do there?

**Comment by haukegr** [comment]
Also, we might want to fix positions of - and + since they appear to change their position when the adjusting number changes its amount of digits.
Try it out for yourself!

**Comment by by-Tim-Christiansen** [comment]
I'm fix this💩 now

**Comment by by-Tim-Christiansen** [comment]
Done ✅ #21
