### ISSUE TITLE
Check readme for mistakes :D

### ISSUE THREAD

**Issue by by-Tim-Christiansen** [by-Tim-Christiansen/pomodoro-clock#20]
Edit Readme.md to show resources and more

**Comment by haukegr** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/c3bd1c53-57b5-43b0-9b0a-444ceb41ad35-36959483-aafe-420f-9d6a-fb6f452d4ec3-v1.png?transparent=1&palette=1&width=246)
