### ISSUE TITLE
Implement pop-up

### ISSUE THREAD

**Issue by haukegr** [by-Tim-Christiansen/pomodoro-clock#23]
What just came to my mind: I want you, Tim, to build me a box!
When the work session ends, I would love to have a small pop-up box that pops up (just what a pop-up usually does) and shows a small message with buttons, where the user is informed that the work session is over and that he may choose whether he wants the break to start or not (that is what the buttons are for).
We might also add this when thebreak has ended and the work session is about to start. It is no secret that I am not quiet into UX, but still, I think this might be a good thing.

To be honest: I just saw this while using a different pomodoro app. 
Let me know what you think!
![bitmoji](https://render.bitstrips.com/v2/cpanel/d436e0aa-e48e-4294-81a9-af3a39b8a276-36959483-aafe-420f-9d6a-fb6f452d4ec3-v1.png?transparent=1&palette=1&width=246)

**Comment by by-Tim-Christiansen** [comment]
I see your point, but I would do some UX changes then just a box.

**Comment by haukegr** [comment]
Tell me if you hit on any ideas!

**Comment by by-Tim-Christiansen** [comment]
U will get what you want

**Comment by haukegr** [comment]
Then why don't you push it? 😞

**Comment by by-Tim-Christiansen** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/f3eb09a8-2a1c-4e30-a204-cd2cca840d18-8cb6eb5c-07f6-40b4-b04b-ac22aa25e7be-v1.png?transparent=1&palette=1&width=246)

**Comment by by-Tim-Christiansen** [comment]
#29 Here is your Box

**Comment by haukegr** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/21759482-c054-4dc5-aaef-e9ce15cf7e3a-1a0997e4-b9be-4c23-a859-ebab082db09d-v1.png?transparent=1&palette=1&width=246)
I will make sure to implement it within the next hours! Thanks! 😃

**Comment by haukegr** [comment]
Popup is implemented and works perfectly.
