### ISSUE TITLE
UI Fixing

### ISSUE THREAD

**Issue by haukegr** [by-Tim-Christiansen/pomodoro-clock#40]
Added several new code-reviews to the SCRUM board yesterday which I would love to have done before launching version v1.0. 
While some of them are pretty code-intensive, there are also a few which aim for a better UI and thus need some design-thinking skills (a skill I never was able to learn). 

This is why I would like you to check the SCRUM board and try to improve the product by working on some of the tasks, mainly improving the UI/UX.

![bitmoji](https://render.bitstrips.com/v2/cpanel/58635206-9a0d-46ba-a152-af31db1e56c1-4f3c5514-debc-41f5-abd9-45eb05dba545-v1.png?transparent=1&palette=1&width=246)

**Comment by by-Tim-Christiansen** [comment]
I'm working on it for V 1.1

**Comment by haukegr** [comment]
Can be closed since we do have another open issue for UI already!
