### ISSUE TITLE
SEO Work

### ISSUE THREAD

**Issue by by-Tim-Christiansen** [by-Tim-Christiansen/pomodoro-clock#43]
We need to focus on our SEO if we want to improve our pageviews. Good SEO Titles, Description and Keywords are key for our small application. It's probably a really good idea to have the explanation text as an "help popup" and meta-descriptions.

Other Opportunities for us would probably be the productive community, where we could do some link building.

**Comment by haukegr** [comment]
I love the idea of building up a community, yet I think it is way too early to think about these things. Howver, for later versions we could build in some kind of log in function to increase the amount of returning visitors to our page - everything measureable with Google Analytics!

**Comment by haukegr** [comment]
Closed for v.1.1.
