### ISSUE TITLE
Feedback Integration

### ISSUE THREAD

**Issue by by-Tim-Christiansen** [by-Tim-Christiansen/pomodoro-clock#45]
We should use some kind of analytics tool to actual learn from ours users. A simple Feedback-form with thumbs up or thumbs down would be cool too. But Privacy and other Terms are probably putting stones right our way. Anyway keep on hacking!

**Comment by haukegr** [comment]
Should not be that much of a problem! All we need is some kind of SSL certification and a safe way to send user data.

**Comment by haukegr** [comment]
Done!
