### ISSUE TITLE
time display right under the circle looks 'boo'! 

### ISSUE THREAD

**Issue by haukegr** [by-Tim-Christiansen/pomodoro-clock#9]
The digital time display (.timeDigital) needs some css-styles!
![image](https://user-images.githubusercontent.com/21065939/34920234-bfc4eb56-f96f-11e7-9376-c96a2bd5ab28.png)

**Comment by by-Tim-Christiansen** [comment]
maybe a lighter font would be better

**Comment by haukegr** [comment]
How about the same color as anything else?
